<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MWLTPF1MEAFD" failures="1" tests="5" name="TestCase1Bonus" time="60.546" errors="0" timestamp="2019-10-06T06:23:18 SAST">
  <testcase classname="automationassignment.TestCase1Bonus" name="step1_EnterAddress" time="8.466"/>
  <testcase classname="automationassignment.TestCase1Bonus" name="step2_SearchForRestaurantsNearAddress" time="15.132"/>
  <testcase classname="automationassignment.TestCase1Bonus" name="step3_AddItemsToBasket" time="8.338"/>
  <testcase classname="automationassignment.TestCase1Bonus" name="step4_CaptureDetailsForDelivery" time="13.796"/>
  <testcase classname="automationassignment.TestCase1Bonus" name="step5_ReceiveOrderReference" time="6.101">
    <failure type="java.lang.AssertionError" message="Pages.pageThankYouForYourOrder().isAt() - Page not found ! did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Pages.pageThankYouForYourOrder().isAt() - Page not found ! did not expect to find [true] but found [false]
at automationassignment.TestCase1Bonus.step5_ReceiveOrderReference(TestCase1Bonus.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- step5_ReceiveOrderReference -->
</testsuite> <!-- TestCase1Bonus -->
