<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MWLTPF1MEAFD" failures="1" tests="5" name="automationassignment.TestCase1Bonus" time="50.430" errors="0" timestamp="2019-10-06T07:20:30 SAST" skipped="0">
  <testcase classname="automationassignment.TestCase1Bonus" name="step1_EnterAddress" time="8.542"/>
  <testcase classname="automationassignment.TestCase1Bonus" name="step5_ReceiveOrderReference" time="6.113">
    <failure message="Pages.pageThankYouForYourOrder().isAt() - Page not found ! did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Pages.pageThankYouForYourOrder().isAt() - Page not found ! did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at automationassignment.TestCase1Bonus.step5_ReceiveOrderReference(TestCase1Bonus.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
    </failure>
  </testcase> <!-- step5_ReceiveOrderReference -->
  <testcase classname="automationassignment.TestCase1Bonus" name="step2_SearchForRestaurantsNearAddress" time="13.325"/>
  <testcase classname="automationassignment.TestCase1Bonus" name="step3_AddItemsToBasket" time="8.183"/>
  <testcase classname="automationassignment.TestCase1Bonus" name="step4_CaptureDetailsForDelivery" time="14.267"/>
</testsuite> <!-- automationassignment.TestCase1Bonus -->
